### ISSUE TITLE
Welcome email edits

### ISSUE THREAD

**Issue by cassaram09** [FreeBreadsticks/onboarding#1]
Overall, documentation looks great. Well written and clear.

I know the welcome email is an example, but I think could be more concise. I removed the part about meetings and shadowing since IMO it's not critical to know immediately. Also rewrote a few things for clarity - for example, we _definitely_ want them to complete the training track before their first shift. My suggestion:

> Hi [NAME]! Welcome to [SQUAD NAME]!
> 
> I am really excited that you are joining our squad and am looking forward to working with you! 
> 
> I have added you to the Technical Coach Training curriculum track, which you can find on Learn.co in the pulldown Curriculum menu. This track will train you on everything you need to know for your role as Technical Coach, so please complete it before your first shift. 
> 
> I have also added you to three channels on Slack: technical-coaches, tc_updates, and tc_support. You can find more information about each of these channels in the training track.
>
> You also have access to Ask A Question, which is where Technical Coaches work with the students during the shift. You can find it on  https://learn.co/expert-chat#. 
> 
> Finally, I have added you to the Learn Instructor App which is found at http://instruction.learn.co/staff/home. There is a lot of good information here so take some time to look through it when you have a chance.
> 
> It may feel like there's a lot of information coming at you, so please feel free to DM me on Slack with any questions. Over the next few days/weeks I'll bring you up to speed on some of the finer details about the Technical Coach role.
>
> Welcome to the team!

**Comment by FreeBreadsticks** [comment]
Changed welcome email - thanks for the input! :)
