### ISSUE TITLE
first week / first day edits

### ISSUE THREAD

**Issue by cassaram09** [FreeBreadsticks/onboarding#2]
Lots of good info here - I think this is a very comprehensive guide to everything we should cover with the new TC before they start. 

We can probably omit the heavy details about qbot, dispatch, and sync as it's all covered in depth in the training track. Might be good to quickly reference it in case they forgot though. 

Also, IMO an experienced TC is anyone who's been doing this for 6+ months ( so a TCL or one of the OG TCs like Josh, PJ, Ian, Kevin, or Ashley) and/or based on their overall star rating from the star rating dashboard.

Lastly, we should be sure to indicate that we should be saving all of the feedback we give them so we have it for reference ( feedback from the mock screenshares as well as when we shadow them).

**Comment by FreeBreadsticks** [comment]
Added changes based on notes -thanks :)
