### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by aisayo** [FreeBreadsticks/onboarding#3]
add quote used for 8-10 hour inactives.
#5 of interface, let TC know that assigning anything to admissions will resolve the questions
#2 of dispatcher goals 'whether' mispelled
#4 dispatcher goals 'exceptionally' mispelled 
#5 dipatch goals 'anything' mispelled
Title `Conversation Flow` mispelled
#2 of managing questions `especially` mispelled
#4 of managing questions should be `time and prevent` but is `time a prevent`
first bullet of `buy yourself time` 'around' is missing a 'd' and following sentence should be 'use this time to greet'

**Comment by FreeBreadsticks** [comment]
Thank you! Fixes/edits made
